version: 2

orbs:
  heroku: circleci/heroku@0.0.10.

jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
      - run:
          command: |
            pipenv install
            pipenv install --dev
      - run:
          command: |
            pipenv run pytest tests
      - run:
          command: |
            heroku login