version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          command: |
            sudo pip install pipenv
            sudo pip install pytest
      - run:
          command: |
            pytest tests
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
          paths:
            - "venv"
      - store_artifacts:
          path: test-reports/
          destination: python_app