version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
      - run:
          command: |
            pipenv install
            pipenv install --dev
      - run:
          command: |
            pipenv run pytest tests
      - run:
          command: |
          sudo apt install snap
            sudo snap install --classic heroku
      - run:
          command: |
            export HEROKU_API_KEY=$HEROKU_API_KEY
            heroku run test_batch_worker
