version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
      - run:
          command: |
            pipenv install
            pipenv install --dev
            source $(pipenv --venv)/bin/activate
      - run:
          command: |
            pipenv run pytest
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - store_artifacts:
          path: test-reports/
          destination: python_app