version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          command: |
            sudo pip install pipenv
            sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
            curl https://pyenv.run | bash
            pipenv install
      - run:
          command: |
            pyenv virtualenv 3.8.0 python-ci
            source ~/.bashrc
            pyenv activate python-ci
            pipenv install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            source ~/.bashrc
            pyenv activate python-ci
            pip install pytest
            pytest tests
      - store_artifacts:
          path: test-reports/
          destination: python_app