on: [push]

name: Code Analyzer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache dependencies & wily build
        uses: actions/cache@v2
        with:
          path: ./wily
          key: wily-analytics-build

      - name: Install wily
        run: |
          ls -a
          pip install wily

      - name: Run wily on code changes
        run: wily -c ./wily build .

      - name: Run wily on changed files
        run: |
          # wily  -c ./wily diff . -r HEAD^2
          for changed_file in {{ steps.files.outputs.all }}; do
            wily -c ./wily diff ${changed_file} -r HEAD^2
          done